
export const blogPosts = [
  {
    id: 1,
    author: "Enzo F.",
    avatar: "https://picsum.photos/seed/enzo/40/40",
    title: "Aggressive 1-Stop Strategy for Monza",
    content: "With low tire degradation at Monza, an aggressive one-stop strategy starting on Softs and switching to Hards around lap 25 could be optimal. This requires a strong qualifying position to maintain track position.\n\nThis approach is risky because a safety car at the wrong time could ruin the strategy completely. However, the time gained by avoiding a second pit stop is often enough to make it a winning move, especially on a high-speed track where track position is king. We've seen it work for multiple teams in the past, provided they have the pace to pull away from the two-stoppers in the first stint.",
    tags: ["Strategy", "Monza"],
    date: "Sep 5, 2023",
  },
  {
    id: 2,
    author: "Adrian N.",
    avatar: "https://picsum.photos/seed/adrian/40/40",
    title: "High Downforce Setup for Monaco",
    content: "Maximizing downforce is key for Monaco's tight corners. A new rear wing design I'm proposing increases surface area without significantly impacting drag on the short straights. See attached schematics.\n\nThe philosophy here is simple: cornering speed is everything in Monaco. The straights are so short that any time lost to drag is easily regained with higher apex speeds. Our simulations show this new wing could provide up to a 5% increase in downforce, which translates to almost two-tenths of a second per lap. The trade-off is a slightly higher fuel consumption, but the potential lap time gain is well worth it.",
    tags: ["Engineering", "Setups"],
    date: "May 22, 2023",
  },
  {
    id: 3,
    author: "Hannah S.",
    avatar: "https://picsum.photos/seed/hannah/40/40",
    title: "Tire Management in Hot Conditions at Bahrain",
    content: "The key to Bahrain is managing rear tire temperatures. A differential setup that allows for more rotation on corner entry can help, but it requires precise driver input to avoid snap oversteer.\n\nWe focus on a technique called 'lift and coast' into heavy braking zones to reduce the load on the rears. Furthermore, a less aggressive throttle map on corner exit can prevent wheelspin, which is a major contributor to thermal degradation. It's a delicate balance between pushing for lap time and preserving the tires for a longer stint.",
    tags: ["Tires", "Driving Style"],
    date: "Mar 12, 2023",
  },
  {
    id: 4,
    author: "Carlos V.",
    avatar: "https://picsum.photos/seed/carlos/40/40",
    title: "Understanding Ground Effect in the New Era",
    content: "The 2022 regulations brought back ground effect aerodynamics, fundamentally changing how cars generate downforce. This article dives into the Venturi tunnels and how teams are exploiting them.\n\nUnlike the old flat floors, the new cars feature large tunnels on either side of the chassis. These tunnels create a low-pressure area underneath the car, effectively sucking it to the track. The main challenge is controlling the ride height. If the car runs too low, the airflow can stall, leading to a sudden loss of downforce—a phenomenon known as 'porpoising'. Teams are constantly working on suspension and floor designs to manage this and maintain a consistent aerodynamic platform.",
    tags: ["Aerodynamics", "Regulations"],
    date: "Oct 15, 2023",
  },
  {
    id: 5,
    author: "Lando N.",
    avatar: "https://picsum.photos/seed/lando/40/40",
    title: "The Art of Late Braking at Spa",
    content: "Spa-Francorchamps' heavy braking zones like La Source and Les Combes are prime overtaking opportunities. We analyze telemetry data to see how the top drivers gain tenths under braking.\n\nThe secret lies in braking later and harder, but also in how the driver modulates the pressure as the car's downforce bleeds off. A common technique is to hit the pedal hard initially and then gradually release it as the car slows down. This 'trail-braking' helps rotate the car into the corner and maximizes the grip from the tires. It's a high-risk, high-reward maneuver that separates the good from the great.",
    tags: ["Driving Style", "Spa"],
    date: "Aug 28, 2023",
  },
  {
    id: 6,
    author: "Yuki T.",
    avatar: "https://picsum.photos/seed/yuki/40/40",
    title: "Engine Modes and Energy Recovery (ERS)",
    content: "A deep dive into the complex world of F1 power units. We explain the different engine modes ('quali mode', race mode) and how ERS deployment is strategized over a lap.\n\nIn qualifying, teams use 'overtake' or 'quali' modes that push the internal combustion engine (ICE) and the MGU-K (Motor Generator Unit - Kinetic) to their absolute limits for a single lap. In the race, it's about balancing energy deployment and recovery. The MGU-H (Motor Generator Unit - Heat) recovers energy from the turbocharger, which can then be deployed by the MGU-K for a power boost. Strategic deployment, such as on corner exits or for defending a position, is crucial for race performance.",
    tags: ["Power Unit", "ERS"],
    date: "Jul 19, 2023",
  },
   {
    id: 7,
    author: "Alex A.",
    avatar: "https://picsum.photos/seed/alex/40/40",
    title: "Simulating a Wet Race at Silverstone",
    content: "Wet weather races are the great equalizer. Using our simulation tools, we explore the crossover point between Intermediate and Full Wet tires at a damp Silverstone circuit.\n\nThe crossover point is the lap time at which it becomes faster to switch from one tire compound to another. Our models take into account factors like the amount of standing water, the rate of track drying, and the car's setup. At Silverstone, the high-speed corners like Maggots and Becketts can hold water for longer, making the crossover decision incredibly tricky. A wrong call can cost upwards of 20 seconds a lap.",
    tags: ["Simulation", "Tires", "Silverstone"],
    date: "Nov 2, 2023",
  },
  {
    id: 8,
    author: "Grace L.",
    avatar: "https://picsum.photos/seed/grace/40/40",
    title: "The Evolution of the F1 Steering Wheel",
    content: "From simple wheels to complex data hubs, the F1 steering wheel is a technological marvel. We trace its evolution and break down all the buttons, rotaries, and switches.\n\nModern wheels have over 25 buttons and switches, controlling everything from brake balance and differential settings to radio communication and the drink system. The central LCD screen provides the driver with a wealth of information, including lap times, gear selection, and engine data. Each wheel is custom-made for the driver's hands and can cost upwards of $50,000.",
    tags: ["Technology", "History"],
    date: "Oct 28, 2023",
  },
  {
    id: 9,
    author: "Daniel R.",
    avatar: "https://picsum.photos/seed/daniel/40/40",
    title: "Porpoising: The Aerodynamic Challenge of 2022",
    content: "The high-frequency bouncing seen in the 2022 season, known as 'porpoising', was a major headache for teams. This post explains the physics behind it and the solutions engineers devised.\n\nThe phenomenon occurs when the ground effect tunnels stall at high speed, causing a sudden loss of downforce. The car then rises, the airflow reattaches, and the process repeats, leading to violent bouncing. Teams have experimented with stiffer suspension setups and modifications to the floor's edge to control this, but it often comes at the cost of overall performance. It's a classic aerodynamic trade-off.",
    tags: ["Aerodynamics", "Engineering"],
    date: "Sep 21, 2023",
  },
];
